name: CI-CD Packer to Terraform EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer

      - name: Install Terraform
        run: |
          sudo apt-get install -y terraform

      - name: Packer Init
        working-directory: packer
        run: packer init .

      - name: Build AMI using Packer
        working-directory: packer
        run: packer build ami.pkr.hcl

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply (Create EC2)
        working-directory: terraform
        run: terraform apply -auto-approve

